### ISSUE TITLE
Does it support sending image?

### ISSUE THREAD

**Issue by naseemr** [ltpitt/notification#1]
How can we send image with pushover?

**Comment by ltpitt** [comment]
Hi @naseemr !

At the moment it does not support images but during the weekend I hope have enough time to give a look and let you know if it will be implemented soon.

Talk to you later :)

**Comment by ltpitt** [comment]
Hi @naseemr !

Very sorry for this late reply but I was busy studying...

I've completed your feature request and it is now possible to send out pushover images too:
`simple-notifications  pushover --subject "test" --body "ciao" --image "/var/www/example/img/money.jpg"`

Let me know if I can help in any way :)
